// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBanner: typeof import('./src/components/TheBanner.vue')['default']
    TheGoodsList: typeof import('./src/components/TheGoodsList.vue')['default']
    TheTabbar: typeof import('./src/components/TheTabbar.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
